---
# Update All Host  
 - hosts: all # below task we want to execute on all our servers; web,db,file servers
   become: true # Will be making changes to system
   pre_tasks: # This task always runs first because it's "pre_task"
 
   - name: update repository index (CentOS) # This is one play. you can have many as you need
     tags: always # I want to run this always and want to patch always 
     dnf: # This is module used for CentOS. Do google to know it's properties
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "CentOS"
 
   - name: install updates (Ubuntu) # This is second play
     tags: always
     apt:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "Ubuntu"

# Create Users on all server
 - hosts: all
   become: true
   roles:
      - base

# Install terraform 
 - hosts: workstations
   become: true
   roles:
      - workstation
 
# Web server group - install apache 
 - hosts: web_servers
   become: true
   roles:
      - web_servers

# DB Server group - install mariadb
 - hosts: db_servers
   become: true
   roles:
      - db_servers

# File Server group - install samba package
 - hosts: file_servers
   tags: samba
   become: true
   roles:
      - file_servers
